### ISSUE TITLE
关于post的支持和js文件加载失败

### ISSUE THREAD

**Issue by jhwqthjy** [soon08/mockjs-webpack-plugin#3]
1. 好像看server文件中对于app没有使用express.json和esxpress.urlencoded进行post等请求没法正确解析请求体中携带参数。
2. 目前没找到问题，当使用.js文件进行载入时，require会报错.

TypeError: Cannot read property 'loaded' of null
    at Function.Module._load (internal/modules/cjs/loader.js:751:23)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at D:\frontend_project\fed.m-change\node_modules\_mockjs-webpack-plugin@3.0.1@mockjs-webpack-plugin\src\routes.js:65:20
    at Layer.handle [as handle_request] (D:\frontend_project\fed.m-change\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\frontend_project\fed.m-change\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\frontend_project\fed.m-change\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\frontend_project\fed.m-change\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
    at next (D:\frontend_project\fed.m-change\node_modules\_express@4.17.1@express\lib\router\index.js:275:10)
    at urlencodedParser (D:\frontend_project\fed.m-change\node_modules\_body-parser@1.19.0@body-parser\lib\types\urlencoded.js:82:7)
    at Layer.handle [as handle_request] (D:\frontend_project\fed.m-change\node_modules\_express@4.17.1@express\lib\router\layer.js:95:5)
    at trim_prefix (D:\frontend_project\fed.m-change\node_modules\_express@4.17.1@express\lib\router\index.js:317:13)
    at D:\frontend_project\fed.m-change\node_modules\_express@4.17.1@express\lib\router\index.js:284:7
    at Function.process_params (D:\frontend_project\fed.m-change\node_modules\_express@4.17.1@express\lib\router\index.js:335:12)
    at next (D:\frontend_project\fed.m-change\node_modules\_express@4.17.1@express\lib\router\index.js:275:10)
    at D:\frontend_project\fed.m-change\node_modules\_body-parser@1.19.0@body-parser\lib\read.js:130:5

**Comment by akazhuo** [comment]
+1
